export type SuperAdminSearchItem = {
  id: string;
  title: string;
  message: string;
  href: string;
  kind: "menu" | "setting" | "link";
};

export const SUPER_ADMIN_SEARCH_ITEMS: SuperAdminSearchItem[] = [
  {
    id: "menu-dashboard",
    title: "Dashboard",
    message: "Open super admin dashboard overview.",
    href: "/dashboard",
    kind: "menu",
  },
  {
    id: "menu-companies",
    title: "Companies",
    message: "Manage platform companies and their details.",
    href: "/companies",
    kind: "menu",
  },
  {
    id: "menu-company-requests",
    title: "New company requests",
    message: "Review and approve new company registrations.",
    href: "/company-requests",
    kind: "menu",
  },
  {
    id: "menu-helpdesk",
    title: "Helpdesk",
    message: "Read and reply to helpdesk requests from dashboard users.",
    href: "/helpdesk",
    kind: "menu",
  },
  {
    id: "menu-users",
    title: "Users",
    message: "View and manage super admin users.",
    href: "/users",
    kind: "menu",
  },
  {
    id: "menu-apis",
    title: "APIs",
    message: "Review backend API security, tenant isolation, and test coverage.",
    href: "/apis",
    kind: "menu",
  },
  {
    id: "menu-orphan-data",
    title: "Orphan data",
    message: "Review orphaned records that need action.",
    href: "/orphan-data",
    kind: "menu",
  },
  {
    id: "menu-website-settings",
    title: "Website settings",
    message: "Manage site logo, dark-mode logo, and favicon shown across all apps.",
    href: "/settings/website",
    kind: "menu",
  },
  {
    id: "setting-website-appearance",
    title: "Appearance & Logos",
    message: "Upload the platform logo and favicon.",
    href: "/settings/website",
    kind: "setting",
  },
  {
    id: "menu-email-configurations",
    title: "Email configurations",
    message: "Edit OTP, invites, and shared email appearance with a guided layout.",
    href: "/settings/email-configurations",
    kind: "menu",
  },
  {
    id: "setting-email-otp",
    title: "Email: OTP",
    message: "Edit the first-time login OTP email template.",
    href: "/settings/email-configurations?tab=otp",
    kind: "setting",
  },
  {
    id: "setting-email-resend-otp",
    title: "Email: Resend OTP",
    message: "Edit the resend OTP email template.",
    href: "/settings/email-configurations?tab=resend_otp",
    kind: "setting",
  },
  {
    id: "setting-email-member-invite",
    title: "Email: Member invite",
    message: "Edit the member invitation email template.",
    href: "/settings/email-configurations?tab=member_invite",
    kind: "setting",
  },
  {
    id: "setting-email-client-invite",
    title: "Email: Client invite",
    message: "Edit the client invitation email template.",
    href: "/settings/email-configurations?tab=client_invite",
    kind: "setting",
  },
  {
    id: "menu-settings",
    title: "Settings",
    message: "Open main platform settings.",
    href: "/settings",
    kind: "menu",
  },
  {
    id: "menu-company-defaults",
    title: "Company defaults",
    message: "Configure defaults used for new companies.",
    href: "/settings/company-defaults",
    kind: "menu",
  },
  {
    id: "menu-widget-management",
    title: "Widget Management",
    message: "Configure dashboard widget icons, previews, and visibility.",
    href: "/settings/widget-management",
    kind: "menu",
  },
  {
    id: "menu-platform-catalog",
    title: "Platform catalog",
    message: "Manage industries, dashboard uses, and skillsets.",
    href: "/settings/platform-catalog",
    kind: "menu",
  },
  {
    id: "menu-faqs",
    title: "HelpDesk FAQs",
    message: "Manage the FAQ entries shown to users on the Helpdesk page.",
    href: "/settings/faqs",
    kind: "menu",
  },
  {
    id: "menu-website-faqs",
    title: "Website FAQs",
    message: "Manage categories, questions and answers for the marketing FAQs page.",
    href: "/settings/website-faqs",
    kind: "menu",
  },
  {
    id: "menu-blogs",
    title: "Blogs",
    message: "Create and manage blog posts for the marketing website.",
    href: "/settings/blog",
    kind: "menu",
  },
  {
    id: "menu-whats-new",
    title: "Website What's new",
    message: "Manage product update timeline entries for the marketing website.",
    href: "/settings/whats-new",
    kind: "menu",
  },
  {
    id: "menu-whats-new-new",
    title: "Add What's new update",
    message: "Create a new product update for the marketing website timeline.",
    href: "/settings/whats-new/new",
    kind: "menu",
  },
  {
    id: "menu-video-tutorials",
    title: "Video tutorials",
    message: "Manage video tutorial categories and lessons for the marketing website.",
    href: "/settings/video-tutorials",
    kind: "menu",
  },
  {
    id: "menu-blogs-new",
    title: "Add blog post",
    message: "Create a new marketing blog article.",
    href: "/settings/blog/new",
    kind: "menu",
  },
  {
    id: "setting-inactivity",
    title: "Inactivity settings",
    message: "Control warning and deletion rules for inactivity.",
    href: "/settings?tab=inactivity",
    kind: "setting",
  },
  {
    id: "setting-other",
    title: "Other settings",
    message: "Open additional settings section.",
    href: "/settings?tab=other",
    kind: "setting",
  },
  {
    id: "setting-company-auto-ids",
    title: "Auto IDs",
    message: "Manage project, employee, and client ID defaults.",
    href: "/settings/company-defaults?tab=bootstrap",
    kind: "setting",
  },
  {
    id: "setting-company-weekend",
    title: "Company weekend defaults",
    message: "Set default weekend days for newly created companies.",
    href: "/settings/company-defaults?tab=weekendDefaults",
    kind: "setting",
  },
  {
    id: "setting-company-contract-models",
    title: "Client contract models",
    message: "Manage default contract models for new companies.",
    href: "/settings/company-defaults?tab=contractModels",
    kind: "setting",
  },
  {
    id: "setting-company-departments",
    title: "Departments",
    message: "Configure department templates for companies.",
    href: "/settings/company-defaults?tab=departments",
    kind: "setting",
  },
  {
    id: "setting-company-designations",
    title: "Designations",
    message: "Configure designation templates for companies.",
    href: "/settings/company-defaults?tab=designations",
    kind: "setting",
  },
  {
    id: "setting-company-activities",
    title: "Timesheet activities",
    message: "Manage default activity types for timesheets.",
    href: "/settings/company-defaults?tab=activities",
    kind: "setting",
  },
  {
    id: "setting-company-leave-types",
    title: "Leave types",
    message: "Configure default leave type templates.",
    href: "/settings/company-defaults?tab=leaveTypes",
    kind: "setting",
  },
  {
    id: "setting-company-default-roles",
    title: "Default roles",
    message: "Set default role mappings for new companies.",
    href: "/settings/company-defaults?tab=defaultRoles",
    kind: "setting",
  },
  {
    id: "setting-company-default-widgets",
    title: "Default Widgets",
    message: "Choose default dashboard widgets for admins, members, and clients.",
    href: "/settings/company-defaults?tab=defaultWidgets",
    kind: "setting",
  },
  {
    id: "setting-company-widgets",
    title: "Widget Management",
    message: "Configure dashboard widget icons, previews, and visibility.",
    href: "/settings/widget-management",
    kind: "setting",
  },
  {
    id: "setting-catalog-industries",
    title: "Industries",
    message: "Manage platform industries and project types.",
    href: "/settings/platform-catalog?tab=industries",
    kind: "setting",
  },
  {
    id: "setting-catalog-dashboard-use",
    title: "Dashboard primary use",
    message: "Manage dashboard primary use options.",
    href: "/settings/platform-catalog?tab=dashboardUses",
    kind: "setting",
  },
  {
    id: "setting-catalog-skillsets",
    title: "Skillsets",
    message: "Manage skill categories and skills.",
    href: "/settings/platform-catalog?tab=skillsets",
    kind: "setting",
  },
  {
    id: "link-profile",
    title: "Profile",
    message: "Open your super admin profile page.",
    href: "/profile",
    kind: "link",
  },
];
